author = "Weru"
baseurl = "https://example.com/"
canonifyurls = true
copyright = "Copyright © 2019, Weru and the Hugo Authors; all rights reserved."
paginate = 6
theme = "newsroom"
title = "Newsroom"
[markup.goldmark.renderer]
hardWraps = false
unsafe = false
xhtml = false
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
noClasses = false
tabWidth = 2
[params]
